INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Tiger Nixon','System Architect','$320,800','2011/04/25','Edinburgh');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Garrett Winters','Accountant','$170,750','2011/07/25','Tokyo');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Ashton Cox','Junior Technical Author','$86,000','2009/01/12','San Francisco');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Cedric Kelly','Senior Javascript Developer','$433,060','2012/03/29','Edinburgh');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Airi Satou','Accountant','$162,700','2008/11/28','Tokyo');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Brielle Williamson','Integration Specialist','$372,000','2012/12/02','New York');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Herrod Chandler','Sales Assistant','$137,500','2012/08/06','San Francisco');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Rhona Davidson','Integration Specialist','$327,900','2010/10/14','Tokyo');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Colleen Hurst','Javascript Developer','$205,500','2009/09/15','San Francisco');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Sonya Frost','Software Engineer','$103,600','2008/12/13','Edinburgh');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Jena Gaines','Office Manager','$90,560','2008/12/19','London');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Quinn Flynn','Support Lead','$342,000','2013/03/03','Edinburgh');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Charde Marshall','Regional Director','$470,600','2008/10/16','San Francisco');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Haley Kennedy','Senior Marketing Designer','$313,500','2012/12/18','London');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Tatyana Fitzpatrick','Regional Director','$385,750','2010/03/17','London');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Michael Silva','Marketing Designer','$198,500','2012/11/27','London');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office)VALUES ('Paul Byrd','Chief Financial Officer (CFO)','$725,000','2010/06/09','New York');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Gloria Little','Systems Administrator','$237,500','2009/04/10','New York');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office)VALUES ('Bradley Greer','Software Engineer','$132,000','2012/10/13','London');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office)VALUES ('Dai Rios','Personnel Lead','$217,500','2012/09/26','Edinburgh');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office)VALUES ('Jenette Caldwell','Development Lead','$345,000','2011/09/03','New York');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office)VALUES ('Yuri Berry','Chief Marketing Officer (CMO)','$675,000','2009/06/25','New York');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office)VALUES ('Caesar Vance','Pre-Sales Support','$106,450','2011/12/12','New York');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Doris Wilder','Sales Assistant','$85,600','2010/09/20','Sydney');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office)VALUES ('Angelica Ramos','Chief Executive Officer (CEO)','$1,200,000','2009/10/09','London');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Gavin Joyce','Developer','$92,575','2010/12/22','Edinburgh');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Jennifer Chang','Regional Director','$357,650','2010/11/14','Singapore');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office)VALUES ('Brenden Wagner','Software Engineer','$206,850','2011/06/07','San Francisco');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Fiona Green','Chief Operating Officer (COO)','$850,000','2010/03/11','San Francisco');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Shou Itou','Regional Marketing','$163,000','2011/08/14','Tokyo');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Michelle House','Integration Specialist','$95,400','2011/06/02','Sydney');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Suki Burks','Developer','$114,500','2009/10/22','London');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Prescott Bartlett','Technical Author','$145,000','2011/05/07','London');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Gavin Cortez','Team Leader','$235,500','2008/10/26','San Francisco');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Martena Mccray','Post-Sales support','$324,050','2011/03/09','Edinburgh');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Unity Butler','Marketing Designer','$85,675','2009/12/09','San Francisco');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Howard Hatfield','Office Manager','$164,500','2008/12/16','San Francisco');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Hope Fuentes','Secretary','$109,850','2010/02/12','San Francisco');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Vivian Harrell','Financial Controller','$452,500','2009/02/14','San Francisco');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Timothy Mooney','Office Manager','$136,200','2008/12/11','London');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Jackson Bradshaw','Director','$645,750','2008/09/26','New York');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Olivia Liang','Support Engineer','$234,500','2011/02/03','Singapore');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Bruno Nash','Software Engineer','$163,500','2011/05/03','London');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Sakura Yamamoto','Support Engineer','$139,575','2009/08/19','Tokyo');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Thor Walton','Developer','$98,540','2013/08/11','New York');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Finn Camacho','Support Engineer','$87,500','2009/07/07','San Francisco');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Serge Baldwin','Data Coordinator','$138,575','2012/04/09','Singapore');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Zenaida Frank','Software Engineer','$125,250','2010/01/04','New York');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Zorita Serrano','Software Engineer','$115,000','2012/06/01','San Francisco');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Jennifer Acosta','Junior Javascript Developer','$75,650','2013/02/01','Edinburgh');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Cara Stevens','Sales Assistant','$145,600','2011/12/06','New York');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Hermione Butler','Regional Director','$356,250','2011/03/21','London');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Lael Greer','Systems Administrator','$103,500','2009/02/27','London');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Jonas Alexander','Developer','$86,500','2010/07/14','San Francisco');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Shad Decker','Regional Director','$183,000','2008/11/13','Edinburgh');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Michael Bruce','Javascript Developer','$183,000','2011/06/27','Singapore');
INSERT INTO EMPLOYEES(name,position,salary,start_date,office) VALUES ('Donna Snider','Customer Support','$112,000','2011/01/25','New York');